package com.daggerfrog.front.api

import akka.event.slf4j.SLF4JLogging
import akka.actor.ActorSystem
import com.typesafe.config.ConfigFactory

object Rosalind extends App{

    //  def myF(str: String, r: Int): List[String] = {
    //  }

    // log.info("Starting workers")
//    def ff(str1: String, str2: String, ind: Int = 0): List[Int] = {
//      val index = str1.indexOf(str2)
//      if (index > -1) index :: f(str1, str2, index)
//      else
//        List.empty
//    }

    //  val str = "CAGCCTACGAACTTCATCCGTGGGACGGTAATGGGCCCCTTATTACAGATTACCTTTTCC\nAATCGCGGAATGCACTGCTGTATTCAAGGGATGCTGCAACCAACAAGCTCCGTATGAAAG\nACGGTGACGAATACGTCGCGAGCACGTTGTACAAGTCCTTGCGAAGGAGTAACGCAGCCT\nGATAAGCTTACAATATTGTGCCCTGCCTTTTGATGACCCCTTGATATCACGGCTGAAGAT\nTAATTCCAAGCATGTTTGGGCAGGTACGGCTAAGCTAGTACAGGTTTTTTAGCGAGCACT\nCCTCGTCAACCCGTCAGAGACATGCCCGCTAGCTGGCTAGGGTATATGCTATAGACGGAT\nATATAATTGTTGCGGGCGTATTCAATAAGCGGGAGTGGCGGTTCAAAGGAAGGCGTTTCC\nGGTCAGGTTGATTATTCGAGGAGACCATCATTCACCTCGCAGTGTCGCCCCCGTAGATTG\nGCCCCTCAGCAGACGGCGCTAAATGTCCCGGTATCACGAACCGGATTGGGCATTTTCGGT\nATGACGCTATCCTGGCCAGCCAGAGGCAGCGCAAGCAATCGGATCCACCGCGTATTTGAT\nTTTGCCGCTTGGAGAGGTTCCGATTATGATACCGTGCAAATAGTGGCGCACGCACTCCGT\nGTACTTTCCCGGAAGTTAGACGCTAACTGAGCTCAGTCACGAGCTTCACCTACGGGTAAG\nGTGGGCCAGTGAAAGCGGATCGGATAATGATCGTTGAGAAGTCAATGCTAAGTTTCACGC\nAAAGGTCAATGGCCTGCGAGCTGTAGGCTCACAACCGGAAAACCCGGAAGAAATCCGGAT\nCACTGGGTAAAAGCTACATAGGACACAGCAGCCGGACTGCCCGGTACCCGACAGGACGGT\nGCTTTGGTTTACTGTAACCGCACAGACGTGCCGGCCCCCGGA".replaceAll("\n", "")
    val source_str =  "A F S Z L X M V I P Y J".split(" ")
    var count = 4
    val r = (1 to count - 1).foldLeft(source_str) {
      case(acc, el) => acc.flatMap{str => str :: source_str.map(el2 => str + el2).toList}
    }
    val na = r.reverse.foldLeft(List.empty[String]){ case(a, b) => if (a.contains(b)) a else b :: a }
    println(na.mkString("\n"))
  }
